"""Markdown generation for venture recommendation reports."""

from __future__ import annotations

from datetime import UTC, datetime

from app.reports.venture.analysis import format_risk_analysis_markdown
from app.reports.venture.funnel import VentureDiscoveryFunnel, build_empty_discovery_explanation
from app.reports.venture.schemas import (
    VentureDiscoveryFunnelSummary,
    VentureOpportunityReport,
    VentureReportContent,
)

REPORT_ENGINE = "venture_report_v1"


class VentureReportGenerator:
    """Builds founder-readable venture recommendation markdown."""

    def build_report(
        self,
        opportunities: list[VentureOpportunityReport],
        *,
        generated_at: datetime | None = None,
        executive_ranking_run_id=None,
        founder_profile_id=None,
        discovery_funnel: VentureDiscoveryFunnel | None = None,
    ) -> VentureReportContent:
        timestamp = generated_at or datetime.now(UTC)
        if opportunities:
            markdown = self.render_markdown(opportunities, generated_at=timestamp)
            outcome = "ranked_opportunities"
            funnel_summary = None
        else:
            funnel = discovery_funnel or VentureDiscoveryFunnel()
            markdown = self.render_empty_discovery_markdown(
                funnel,
                generated_at=timestamp,
            )
            outcome = "empty_discovery"
            funnel_summary = VentureDiscoveryFunnelSummary.model_validate(
                funnel.model_dump()
            )
        return VentureReportContent(
            markdown=markdown,
            executive_ranking_run_id=executive_ranking_run_id,
            founder_profile_id=founder_profile_id,
            opportunities=opportunities,
            generated_count=len(opportunities),
            outcome=outcome,
            discovery_funnel=funnel_summary,
        )

    def render_empty_discovery_markdown(
        self,
        funnel: VentureDiscoveryFunnel,
        *,
        generated_at: datetime,
    ) -> str:
        lines = [
            "# Venture Recommendation Report",
            "",
            "Discovery completed without founder-grade ranked opportunities. "
            "This is a valid outcome when signal evidence does not support a venture thesis.",
            "",
            f"**Generated:** {generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
            f"**Opportunities covered:** 0",
            "",
            "---",
            "",
            "## Discovery funnel",
            "",
            f"- **Signals collected:** {funnel.signals_collected}",
            f"- **Complaints extracted:** {funnel.complaints_extracted}",
            f"- **Patterns found:** {funnel.patterns_found}",
            f"- **Opportunities generated:** {funnel.opportunities_generated}",
            f"- **Ranked opportunities:** {funnel.ranked_opportunity_count}",
            "",
            "## Why no founder-grade opportunities",
            "",
        ]
        lines.extend(build_empty_discovery_explanation(funnel))
        lines.extend(
            [
                "",
                "---",
                "",
                "_Report generated by AI Venture Studio. Re-run discovery after "
                "collecting additional coherent complaint evidence._",
            ]
        )
        return "\n".join(lines)

    def render_markdown(
        self,
        opportunities: list[VentureOpportunityReport],
        *,
        generated_at: datetime,
    ) -> str:
        lines = [
            "# Venture Recommendation Report",
            "",
            "A decision-ready summary of the top ranked opportunities in your pipeline.",
            "",
            f"**Generated:** {generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
            f"**Opportunities covered:** {len(opportunities)}",
            "",
            "---",
            "",
        ]

        if not opportunities:
            lines.append(
                "_No ranked opportunities in this report payload. "
                "Use build_report with discovery_funnel for empty-outcome runs._"
            )
            return "\n".join(lines)

        lines.extend(
            [
                "## Executive summary",
                "",
                "The opportunities below are ranked by composite score across customer pain, "
                "market size, revenue potential, competitive position, growth outlook, and "
                "founder fit. Each section pulls from completed agent analyses.",
                "",
            ]
        )

        for report in opportunities:
            lines.extend(self._render_opportunity(report))

        lines.extend(
            [
                "---",
                "",
                "_Report generated by AI Venture Studio. Validate assumptions with customers "
                "before committing build time._",
            ]
        )
        return "\n".join(lines)

    def _render_opportunity(self, report: VentureOpportunityReport) -> list[str]:
        score_line = (
            f"**Composite score:** {report.final_opportunity_score}/100 · "
            f"Pain {report.pain_score or '—'} · Market {report.market_score or '—'} · "
            f"Revenue {report.revenue_score or '—'} · "
            f"Competition {report.competition_score or '—'} · "
            f"Growth {report.growth_score or '—'} · "
            f"Founder fit {report.founder_fit_score or '—'}"
        )

        lines = [
            f"## {report.rank}. {report.title}",
            "",
            score_line,
            "",
            "### Recommendation",
            report.recommendation,
            "",
            "### Opportunity summary",
            report.opportunity_summary,
            "",
            "### Market analysis",
            report.market_analysis,
            "",
            "### Competitor analysis",
            report.competitor_analysis,
            "",
            "### Customer evidence",
        ]

        if not report.customer_evidence:
            lines.append("_No customer evidence linked._")
        else:
            for item in report.customer_evidence:
                lines.append(self._format_evidence_item(item))

        lines.extend(
            [
                "",
                "### Revenue analysis",
                report.revenue_analysis,
                "",
                "### MVP plan",
                report.mvp_plan,
                "",
                "### Go-to-market strategy",
                report.go_to_market_strategy,
                "",
                "### Growth strategy",
                report.growth_strategy,
                "",
                "### Founder fit analysis",
                report.founder_fit_analysis,
                "",
                "### Risk analysis",
                format_risk_analysis_markdown(report.risk_analysis),
                "",
                "---",
                "",
            ]
        )
        return lines

    @staticmethod
    def _format_evidence_item(item) -> str:
        summary = (item.summary or "").strip()
        quote = (item.verbatim_quote or "").strip()
        url_suffix = f" ([source]({item.source_url}))" if item.source_url else ""

        if not quote or quote == summary or quote in summary:
            body = summary or quote or "_No quote captured._"
            return f"- **Severity {item.severity}/5** — {body}{url_suffix}"

        return (
            f"- **Severity {item.severity}/5** — {summary}  \n"
            f'  > "{quote}"{url_suffix}'
        )
