"""Markdown generation for venture recommendation reports."""

from __future__ import annotations

from datetime import UTC, datetime

from app.reports.venture.analysis import format_risk_analysis_markdown
from app.reports.venture.schemas import VentureOpportunityReport, VentureReportContent

REPORT_ENGINE = "venture_report_v1"


class VentureReportGenerator:
    """Builds founder-readable venture recommendation markdown."""

    def build_report(
        self,
        opportunities: list[VentureOpportunityReport],
        *,
        generated_at: datetime | None = None,
        executive_ranking_run_id=None,
        founder_profile_id=None,
    ) -> VentureReportContent:
        timestamp = generated_at or datetime.now(UTC)
        markdown = self.render_markdown(opportunities, generated_at=timestamp)
        return VentureReportContent(
            markdown=markdown,
            executive_ranking_run_id=executive_ranking_run_id,
            founder_profile_id=founder_profile_id,
            opportunities=opportunities,
            generated_count=len(opportunities),
        )

    def render_markdown(
        self,
        opportunities: list[VentureOpportunityReport],
        *,
        generated_at: datetime,
    ) -> str:
        lines = [
            "# Venture Recommendation Report",
            "",
            "A decision-ready summary of the top ranked opportunities in your pipeline.",
            "",
            f"**Generated:** {generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
            f"**Opportunities covered:** {len(opportunities)}",
            "",
            "---",
            "",
        ]

        if not opportunities:
            lines.append("_No ranked opportunities available. Run executive ranking first._")
            return "\n".join(lines)

        lines.extend(
            [
                "## Executive summary",
                "",
                "The opportunities below are ranked by composite score across customer pain, "
                "market size, revenue potential, competitive position, growth outlook, and "
                "founder fit. Each section pulls from completed agent analyses.",
                "",
            ]
        )

        for report in opportunities:
            lines.extend(self._render_opportunity(report))

        lines.extend(
            [
                "---",
                "",
                "_Report generated by AI Venture Studio. Validate assumptions with customers "
                "before committing build time._",
            ]
        )
        return "\n".join(lines)

    def _render_opportunity(self, report: VentureOpportunityReport) -> list[str]:
        score_line = (
            f"**Composite score:** {report.final_opportunity_score}/100 · "
            f"Pain {report.pain_score or '—'} · Market {report.market_score or '—'} · "
            f"Revenue {report.revenue_score or '—'} · Competition {report.competition_score or '—'} · "
            f"Growth {report.growth_score or '—'} · Founder fit {report.founder_fit_score or '—'}"
        )

        lines = [
            f"## {report.rank}. {report.title}",
            "",
            score_line,
            "",
            f"### Recommendation",
            report.recommendation,
            "",
            "### Opportunity summary",
            report.opportunity_summary,
            "",
            "### Market analysis",
            report.market_analysis,
            "",
            "### Competitor analysis",
            report.competitor_analysis,
            "",
            "### Customer evidence",
        ]

        if not report.customer_evidence:
            lines.append("_No customer evidence linked._")
        else:
            for item in report.customer_evidence:
                url = f" ([source]({item.source_url}))" if item.source_url else ""
                lines.append(
                    f"- **Severity {item.severity}/5** — {item.summary} "
                    f'"{item.verbatim_quote}"{url}'
                )

        lines.extend(
            [
                "",
                "### Revenue analysis",
                report.revenue_analysis,
                "",
                "### MVP plan",
                report.mvp_plan,
                "",
                "### Go-to-market strategy",
                report.go_to_market_strategy,
                "",
                "### Growth strategy",
                report.growth_strategy,
                "",
                "### Founder fit analysis",
                report.founder_fit_analysis,
                "",
                "### Risk analysis",
                format_risk_analysis_markdown(report.risk_analysis),
                "",
                "---",
                "",
            ]
        )
        return lines
